# Stage 1: Builder
FROM node:20-alpine AS builder

ARG PRISMA_CLI_QUERY_ENGINE_TYPE=binary
ENV PRISMA_CLI_QUERY_ENGINE_TYPE=$PRISMA_CLI_QUERY_ENGINE_TYPE

WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
COPY schema.prisma ./

# Install dependencies and Generate Prisma Client
RUN npm ci && \
    PRISMA_CLI_QUERY_ENGINE_TYPE=library PRISMA_CLIENT_ENGINE_TYPE=library npx prisma generate

# Copy source code and build the application
COPY . .
RUN npx nest build && \
    npm prune --production

# Stage 2: Production
FROM node:20-alpine AS production

WORKDIR /usr/src/app

RUN apk add --no-cache openssl


# Copy built assets and dependencies from builder
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/package-lock.json ./
COPY --from=builder /usr/src/app/schema.prisma ./

# Set environment to production
ENV NODE_ENV=production

# Expose port (Appetite Service uses 4012)
EXPOSE 4012

# Start the application
CMD ["node", "dist/src/main"]
