# Stage 1: Builder
FROM node:20-alpine AS builder

WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
COPY schema.prisma ./

# Install all dependencies (including dev for building)
RUN npm ci

# Generate Prisma Client
RUN npx prisma generate

# Copy source code
COPY . .

# Build the application
RUN npx nest build

# Prune dev dependencies
RUN npm prune --production

# Stage 2: Production
FROM node:20-alpine AS production

WORKDIR /usr/src/app

RUN apk add --no-cache openssl


# Copy built assets and dependencies from builder
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/schema.prisma ./

# Set environment to production
ENV NODE_ENV=production

# Expose port (Monitoring Service uses 4010)
EXPOSE 4010

# Start the application
CMD ["node", "dist/src/main"]
